directories:
  output: dist-electron
  buildResources: build
appId: com.eckerdt.grantmanager
productName: Eckerdt Grant Manager
files:
  - filter:
      - dist/**/*
      - electron/**/*
win:
  target: nsis
  icon: public/icon.ico
electronVersion: 28.3.3
